<?php
ob_start("ob_gzhandler");
date_default_timezone_set("Africa/Algiers");
error_reporting(E_ALL);
set_time_limit(0);
include "Functions.php";
$conn = openConnection();
$iconn = openIConnection();
displayToday();
getNow();
print "\n\nScript Started: " . displayToday() . ", " . getNow() . " HRS";
flush();
if (checkMAC($conn)) {
    $query = "SELECT EX1, MACAddress, CompanyName, DBType, DBName, DBUser, DBPass, MealCouponPrinterName FROM OtherSettingMaster";
    $result = selectData($conn, $query);
    $mysqlpath = $result[7];
    echo "\n\rFound MySQL: " . $mysqlpath;
    exec("\"" . $mysqlpath . "\\mysqlcheck\" Access --user=" . decryptString($db_user) . " --password=" . decryptString($db_pass));
//    exec("\"" . $mysqlpath . "\\mysqlcheck\" unis --user=" . decryptString($db_user) . " --password=" . decryptString($db_pass));
    exec("\"" . $mysqlpath . "\\mysqlcheck\" AccessArchive --user=" . decryptString($db_user) . " --password=" . decryptString($db_pass));
   exec("\"" . $mysqlpath . "\\mysqlcheck\" UNIS --user=unisuser --password=unisamho");
    // exec("\"" . $mysqlpath . "\\mysqlcheck\" unis --user=root --password=namaste");
    $query = "ALTER TABLE AttendanceMaster";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE DayMaster";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE EmployeeFlag";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE tuser";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE tenter";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE FlagDayRotation";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE Transact";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE PreApproveOT";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE ProcessLog";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE ShiftRotateLog";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE ShiftRoster";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE event";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE relateditems";
    updateIData($iconn, $query, true);
    $query = "ALTER TABLE SRA";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE AttendanceMaster";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE DayMaster";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE EmployeeFlag";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE tuser";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE tenter";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE FlagDayRotation";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE Transact";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE PreApproveOT";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE ProcessLog";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE ShiftRotateLog";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE ShiftRoster";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE event";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE relateditems";
    updateIData($iconn, $query, true);
    $query = "OPTIMIZE TABLE SRA";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE AttendanceMaster";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE DayMaster";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE tuser";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE tenter";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE FlagDayRotation";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE Transact";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE PreApproveOT";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE ProcessLog";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE ShiftRotateLog";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE ShiftRoster";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE EmployeeFlag";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE event";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE relateditems";
    updateIData($iconn, $query, true);
    $query = "FLUSH TABLE SRA";
    updateIData($iconn, $query, true);
    $query = "INSERT INTO ProcessLog (PType, PDate, PTime) VALUES ('DB Maintenance', " . insertToday() . ", '" . getNow() . "')";
    updateIData($iconn, $query, true);
    print "DB Maintenance Complete";
} else {
    print "Un Registered Application. Process Terminated.";
}
displayToday();
getNow();
print "\n\nScript Ended: " . displayToday() . ", " . getNow() . " HRS";
flush();

?>